urls <- c(
https://receita.economia.gov.br/dados/resultados/atendimento/2019/relatorio-mensal-março-2019-capa.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2019/relatorio-mensal-fevereiro-2019.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2019/relatorio-mensal-janeiro-2019.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-mensal%20-%20Janeiro-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/nota-cogea-n-13-relatorio-mensal-fevereiro-2018-com-capa.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-mensal-marco-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-mensal-abril-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/nota-cogea-no-42-relatorio-mensal-maio-2018-capa.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/nota-cogea-no-44-relatorio-mensal-junho-2018-com-capa.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-de-atendimento-julho-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-mensal-agosto-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-mensal-de-atendimento-setembro-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/nota-cogea-no-69-relatorio-mensal-outubro-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/nota-cogea-n-74-relatorio-mensal-novembro-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2018/relatorio-mensal-dezembro-2018.pdf,/view
https://receita.economia.gov.br/dados/resultados/atendimento/2017/nota-coaef-no-04-relatorio-mensal-janeiro-2017-com-capa.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/RelatorioMensalfevereiro2017.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/nota-coaef-no-11-relatorio-mensal-marco-2017.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/Relatorio%20Mensal%20-%20Abril%202017.pdf,  
https://receita.economia.gov.br/dados/resultados/atendimento/2017/relatorio-mensal-maio-2017.pdf,  
https://receita.economia.gov.br/dados/resultados/atendimento/2017/relatorio-mensal-junho-2017.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2017/relatorio-mensal-julho-2017.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/relatorio-do-atendimento-agosto-2017.pdf, "
https://receita.economia.gov.br/dados/resultados/atendimento/2017/nota-cogea-relatorio-mensal-setembro-2017.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/RelatrioMensaldeAtendimentoOutubro2017.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/relatorio-mensal-novembro-2017.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2017/Relatorio-mensal-dezembro-2017-com-capa.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/relatorio-mensal-janeiro-2016-l.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/copy_of_RelatrioMensalFevereiro2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/copy_of_RelatrioMensalMaro2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/RelatrioMensalAbril2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/RelatrioMensalMaio2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/RelatrioMensalJunho2016L.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2016/RelatrioMensalJulho2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/relatorio-mensal-agosto-2016.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2016/nota-coaef-no-34-relatorio-mensal-setembro-2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/relatorio-mensal-novembro-2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/nota-coaef-no-37-relatorio-mensal-outubro2016.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2016/relatorio-mensal-dezembro-2016.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2015/copy_of_RelatrioMensalSetembro.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2015/copy_of_RelatrioMensalOutubro.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2015/copy_of_RelatrioMensalNovembro.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2015/RelatrioMensalDezembro.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/TransparencianoAtendimentoJan2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/TransparencianoAtendimentoFev2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/TransparencianoAtendimentoMar2014.pdf, 
https://receita.economia.gov.br/dados/resultados/atendimento/2014/TransparencianoAtendimentoAbr2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/transparencianoatendimentomai2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/transparencianoatendimentojun2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/transparencianoatendimentojul2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/transparencianoatendimentoago2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/transparencianoatendimentoset2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2014/transparencianoatendimentoout2014.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoJan2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoFev2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoMar2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoAbr2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoMai2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoJun2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoJul2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoAgo2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoSet2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoOut2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoNov2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2013/TransparencianoAtendimentoDez2013.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoAbr2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoMai2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoJun2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoJul2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoJun2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoAgo2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoSet2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoOut2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoNov2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoDez2012.pdf,
https://receita.economia.gov.br/dados/resultados/atendimento/2012/TransparencianoAtendimentoDez2012.pdf
)
